##### This if for Firewall #####

#---
#
#This is a playbook for Firewall Rules
#

#- hosts: all
#  remote_user: root

#  tasks:
#    - name: Enable ufw
#      command: ufw enable
 
#    - name: Allow 9200
#      command: ufw allow 9200

#    - name: Allow 22
#      command: ufw allow 22
   
#    - name: Allow http
#      command: ufw allow http

#    - name: Allow https
#      command: ufw allow https

#    - name: Reload ufw
#      command: ufw reload


#### Install Elasticsearch (ALL NODE) ####

---
#
#This if for install elasticsearch 
#

- hosts: all
  remote_user: root

  tasks:
    - name: Get Elasticsearch
      command: wget https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.2.0/elasticsearch-2.2.0.deb

    - name: Install Elasticsearch
      command: sudo dpkg -i elasticsearch-2.2.0.deb

    - name: Start Elasticsearch
      command: systemctl start elasticsearch.service

    - name: Enable Elasticsearch
      command: systemctl enable elasticsearch.service

    - name: Restart Elasticsearch
      command: systemctl restart elasticsearch.service

    - pause:
        seconds: 30

    - name: Install Curl 
      command: apt-get install curl -y

    - name: Check Elasticsearch Alivness
      command: curl http://localhost:9200


#### Elasticsearch.yml Edit (MASTER NODE) ####

#---
#
#This if for editiing of elasticsearch.yml 
#

- hosts: Master
  remote_user: root

  tasks:
    - name: Cluster Name
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#cluster.name: my-application'
        line: 'cluster.name: Production'

    - name: Node Name
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#node.name: node-1'
        line: 'node.name: elkclustermaster'

    - name: Node Master TRUE
      lineinfile: 
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '^node.name: elkclustermaster'
        insertafter: '^node.name: elkclustermaster'
        line: 'node.master: true'

    - name: Node Data FALSE 
      lineinfile: 
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '^node.master: true'
        insertafter: '^node.master: true'
        line: 'node.data: false'

    - name: Network Host
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#network.host: 192.168.0.1'
        line: 'network.host: 192.168.2.192'

    - name: Discovery 1
      lineinfile: 
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '^# The default list of hosts is ["127.0.0.1", "[::1]"]'
        insertafter: '^# The default list of hosts is ["127.0.0.1", "[::1]"]'
        line: 'discovery.zen.ping.multicast.enabled: false'

    - name: Discovery 2
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#discovery.zen.ping.unicast.hosts: ["host1", "host2"]'
        line: 'discovery.zen.ping.unicast.hosts: ["elkclusterclient", "elkclustermaster","elkclusterdata"]'

    - name: Restart Elasticsearch
      command: systemctl restart elasticsearch.service

    - pause:
        seconds: 30


#### Elasticsearch.yml Edit (CLIENT NODE) ####

#---
#
#This if for editiing of elasticsearch.yml 
#

- hosts: Client
  remote_user: root

  tasks:
    - name: Cluster Name
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#cluster.name: my-application'
        line: 'cluster.name: Production'

    - name: Node Name
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#node.name: node-1'
        line: 'node.name: elkclusterclient'

    - name: Node Client TRUE
      lineinfile: 
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '^node.name: elkclusterclient'
        insertafter: '^node.name: elkclusterclient'
        line: 'node.client: true'

    - name: Node Data FALSE 
      lineinfile: 
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '^node.client: true'
        insertafter: '^node.client: true'
        line: 'node.data: false'

    - name: Network Host
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#network.host: 192.168.0.1'
        line: 'network.host: 192.168.2.193'

    - name: Discovery 1
      lineinfile: 
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '^# The default list of hosts is ["127.0.0.1", "[::1]"]'
        insertafter: '^# The default list of hosts is ["127.0.0.1", "[::1]"]'
        line: 'discovery.zen.ping.multicast.enabled: false'

    - name: Discovery 2
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#discovery.zen.ping.unicast.hosts: ["host1", "host2"]'
        line: 'discovery.zen.ping.unicast.hosts: ["elkclusterclient", "elkclustermaster","elkclusterdata"]'

    - name: Restart Elasticsearch
      command: systemctl restart elasticsearch.service

    - pause:
        seconds: 30


#### Elasticsearch.yml Edit (DATA NODE) ####

#---
#
#This if for editiing of elasticsearch.yml 
#

- hosts: Data
  remote_user: root

  tasks:
    - name: Cluster Name
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#cluster.name: my-application'
        line: 'cluster.name: Production'

    - name: Node Name
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#node.name: node-1'
        line: 'node.name: elkclusterdata'

    - name: Node Client FALSE
      lineinfile: 
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '^node.name: elkclusterdata'
        insertafter: '^node.name: elkclusterdata'
        line: 'node.client: false'

    - name: Node Data TRUE 
      lineinfile: 
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '^node.client: false'
        insertafter: '^node.client: false'
        line: 'node.data: true'

    - name: Network Host
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#network.host: 192.168.0.1'
        line: 'network.host: 192.168.2.194'

    - name: Discovery 1
      lineinfile: 
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '^# The default list of hosts is ["127.0.0.1", "[::1]"]'
        insertafter: '^# The default list of hosts is ["127.0.0.1", "[::1]"]'
        line: 'discovery.zen.ping.multicast.enabled: false'

    - name: Discovery 2
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: '#discovery.zen.ping.unicast.hosts: ["host1", "host2"]'
        line: 'discovery.zen.ping.unicast.hosts: ["elkclusterclient", "elkclustermaster","elkclusterdata"]'

    - name: Restart Elasticsearch
      command: systemctl restart elasticsearch.service

    - pause:
        seconds: 30


#### Limit.conf Edit (ALL NODE) ####

#---
#
#This if for editiing of limit.conf
#

#- hosts: all
#  remote_user: root

#  tasks:
#    - name: Add 1
#      lineinfile: 
#        destfile: /etc/security/limits.conf
#        regexp: '^# End of file'
#        insertafter: '^# End of File'
#        line: '*           soft     nofile     64000'

#    - name: Add 2
#      lineinfile: 
#        destfile: /etc/security/limits.conf
#        regexp: '^*           soft     nofile     64000'
#        insertafter: '^*           soft     nofile     64000'
#        line: '*           hard     nofile     64000'

#    - name: Add 3
#      lineinfile: 
#        destfile: /etc/security/limits.conf
#        regexp: '^*           hard     nofile     64000'
#        insertafter: '^*           hard     nofile     64000'
#        line: 'root     soft     nofile     64000'

#    - name: Add 4
#      lineinfile: 
#        destfile: /etc/security/limits.conf
#        regexp: '^root     soft     nofile     64000'
#        insertafter: '^root     soft     nofile     64000'
#        line: 'root     hard     nofile     64000'

#    - pause:
#        seconds: 30



#### pam.d Edit (ALL NODE) ####

#---
#
#This if for editiing of pam.d 
#

- hosts: all
  remote_user: root

  tasks:
    - name: Edit 1
      lineinfile:
        destfile: /etc/pam.d/common-session
        regexp: '^session required                        pam_permit.so'
        insertafter: '^session required                        pam_permit.so'
        line: 'session required                        pam_limits.so'

    - name: Edit 2
      lineinfile:
        destfile: /etc/pam.d/common-session-noninteractive
        regexp: '^session required                        pam_permit.so'
        insertafter: '^session required                        pam_permit.so'
        line: 'session required                        pam_limits.so'

    - name: Restart Elasticsearch
      command: systemctl restart elasticsearch.service

    - pause:
        seconds: 30


#### Environment Edit (ALL NODE) ####

##---
#
#This if for editiing of environment
#

- hosts: all
  remote_user: root

  tasks:
    - name: Edit 
      lineinfile:
        destfile: /etc/environment
        regexp: '^PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"'
        insertafter: '^PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"'
        line: 'ES_HEAP_SIZE="512M"'

    - name: Restart Elasticsearch
      command: systemctl restart elasticsearch.service

    - pause:
        seconds: 30


#### Last Check Elasticsearch (ALL NODE) ####

##---
#
#This if for install elasticsearch 
#

- hosts: all
  remote_user: root

  tasks:
    - name: Check Master Elasticsearch
      command: curl http://elkclustermaster:9200/_cluster/stats?pretty

    - name: Check Client Elasticsearch
      command: curl http://elkclusterclient:9200/_cluster/stats?pretty

    - name: Check Data Elasticsearch
      command: curl http://elkclusterdata:9200/_cluster/stats?pretty





