##### This if for Firewall #####

---
#
#This is a playbook for Firewall Rules
#

- hosts: testers
  remote_user: root

  tasks:
    - name: Enable firewalld
      service: name=firewalld state=started enabled=yes

    - name: Allow http/https
      command: firewall-cmd --zone=public --permanent --add-service=http --add-service=https

    - name: Allow port 5044 TCP/UDP
      command: firewall-cmd --zone=public --add-port=5044/tcp --add-port=5044/udp --permanent

    - name: Allow port 5000 TCP/UDP
      command: firewall-cmd --zone=public --add-port=5000/tcp --add-port=5000/udp --permanent

    - name: Allow port 10051 TCP/UDP
      command: firewall-cmd --zone=public --permanent --add-port=10051/tcp --add-port=10051/udp

    - name: Allow port 5601 TCP/UDP - Kibana
      command: firewall-cmd --zone=public --add-port=5601/tcp --add-port=5601/udp --permanent

    - name: Allow port 9200 TCP/UDP - Elasticsearch
      command: firewall-cmd --zone=public --add-port=9200/tcp --add-port=9200/udp --permanent

    - name: Allow port 9300 TCP/UDP - Elasticsearch
      command: firewall-cmd --zone=public --add-port=9300/tcp --add-port=9300/udp --permanent

    - name: Allow port 80 TCP/UDP - HTTP/HTTPS
      command: firewall-cmd --zone=public --add-port=80/tcp --add-port=80/udp --permanent

    - name: Allow port 514 TCP/UDP - Syslog
      command: firewall-cmd --zone=public --add-port=514/tcp --add-port=514/udp --permanent

    - name: Allow port 10514 TCP/UDP - Syslog
      command: firewall-cmd --zone=public --add-port=10514/tcp --add-port=10514/udp --permanent

    - name: Allow port 5043 TCP/UDP - SOPHOS
      command: firewall-cmd --zone=public --add-port=5043/tcp --add-port=5043/udp --permanent

    - name: Allow port 161 TCP/UDP - SNMP
      command: firewall-cmd --zone=public --add-port=161/tcp --add-port=161/udp --permanent

    - name: Allow port logstash-forwarder port 
      command: firewall-cmd --permanent --add-forward-port=port=80:proto=tcp:toport=5601


#    - name: Allow port *** TCP/UDP - EXTRA PORTS Commands
#      command: firewall-cmd --zone=public --add-port=***/tcp --add-port=***/udp --permanent

    - name: Reload Firewall
      service: name=firewalld state=restarted



##### This is for Java Update #####

##---
#
#This if for Updating of Java 1.8
#

- hosts: testers
  remote_user: root

  tasks:
    - name: Install Java 1.8
      command: yum -y install java-1.8.0-openjdk.x86_64


##### This is The ELK Part ######
### All installation is done via RPM ###

##---
#
#This is Elasticsearch v6.0.1
#

- hosts: testers
  remote_user: root

  tasks:
    - name: Download Elasticsearch
      command: wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.1.rpm
      ignore_errors: true
      become: true

    - name: Import GPG-Key
      command: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
      ignore_errors: true
      become: true

    - name: Install Elasticsearch RPM
      command: rpm --install elasticsearch-6.0.1.rpm
      ignore_errors: true
      become: true

    - name: Restart Daemon
      command: systemctl daemon-reload

    - name: Enable Elasticsearch
      command: systemctl enable elasticsearch.service

    - name: Start Elasticsearch
      command: systemctl start elasticsearch.service

    - pause:
        seconds: 30

    - name: Restart Elasticsearch
      command: systemctl restart elasticsearch.service

    - name: Restart firewalld
      command: systemctl restart firewalld.service

    - name: Restart daemon
      command: systemctl daemon-reload

    - pause:
        seconds: 30

    - name: Check Elasticsearch Service Aliveness
      command: curl -X GET http://localhost:9200
      ignore_errors: true
      become: true


##---
#
#This is Kibana v6.0.1
#

- hosts: testers
  remote_user: root

  tasks:
    - name: Download Kibana
      command: wget https://artifacts.elastic.co/downloads/kibana/kibana-6.0.1-x86_64.rpm
      ignore_errors: true
      become: true

    - name: Install Kibana RPM
      command: rpm --install kibana-6.0.1-x86_64.rpm
      ignore_errors: true
      become: true

    - name: Edit Kibana port to Open in config file
      lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: '#server.port'
        line: 'server.port: 5601'

    - name: Edit Kibana host to 192.168.2.181
      lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: '#server.host'
        line: 'server.host: 192.168.2.199'

    - name: Restart Daemon
      command: systemctl daemon-reload

    - name: Start Kibana
      command: systemctl start kibana.service

    - name: Enable Kibana
      command: systemctl enable kibana.service

    - pause:
        seconds: 30

    - name: Restart Elasticsearch
      command: systemctl restart elasticsearch.service

    - name: Restart Kibana
      command: systemctl restart kibana.service

    - name: Restart firewalld
      command: systemctl restart firewalld.service

    - name: Restart daemon
      command: systemctl daemon-reload


##---
#
#This is Logstash v6.0.1
#

- hosts: testers
  remote_user: root

  tasks:
    - name: Download Logstash
      command: wget https://artifacts.elastic.co/downloads/logstash/logstash-6.0.1.rpm
      ignore_errors: true
      become: true

    - name: Import GPG-Key
      command: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
      ignore_errors: true
      become: true

    - name: Install Logstash RPM
      command: rpm --install logstash-6.0.1.rpm
      ignore_errors: true
      become: true

    - name: Restart Daemon
      command: systemctl daemon-reload

    - name: Start Logstash
      command: systemctl start logstash.service

    - name: Enable Logstash
      command: systemctl enable logstash.service

    - pause:
        seconds: 30

    - name: Restart Elasticsearch
      command: systemctl restart elasticsearch.service

    - name: Restart Kibana
      command: systemctl restart kibana.service

    - name: Restart Logstash
      command: systemctl restart logstash.service

    - name: Restart firewalld
      command: systemctl restart firewalld.service

    - name: Restart daemon
      command: systemctl daemon-reload



### This is the Secation for Beats Components ###

##---
#
#This is Packetbeat v6.0.1
#

- hosts: testers
  remote_user: root

  tasks:
    - name: Install libpcap
      command: yum install libpcap

    - name: Download Packetbeat
      command: wget https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-6.0.1-x86_64.rpm
      ignore_errors: true
      become: true

    - name: Install Packetbeat
      command: yum -y install packetbeat-6.0.1-x86_64.rpm
      ignore_errors: true
      become: true

    - name: Edit Kibana port to Open in config file
      lineinfile:
        destfile: /etc/packetbeat/packetbeat.yml
        line: 'host:"192.168.2.199:5601"'
        insertafter: '^setup.kibana:'

    - name: Start Packetbeat
      command: systemctl start packetbeat.service

    - name: Enable Packetbeat
      command: systemctl enable packetbeat.service

    - pause:
        seconds: 30


##---
#
#This is Metricbeat v6.0.1
#

- hosts: testers
  remote_user: root

  tasks:
    - name: Download Metricbeat
      command: wget https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.0.1-x86_64.rpm
      ignore_errors: true
      become: true

    - name: Install Packetbeat
      command: yum -y install metricbeat-6.0.1-x86_64.rpm
      ignore_errors: true
      become: true

    - name: Edit Kibana port to Open in config file
      lineinfile:
        destfile: /etc/metricbeat/metricbeat.yml
        line: 'host:"192.168.2.199:5601"'
        insertafter: '^setup.kibana:'

    - name: Start Metricbeat
      command: systemctl start metricbeat.service

    - name: Enable Metricbeat
      command: systemctl enable metricbeat.service

    - pause:
        seconds: 30

    - name: Restart Elasticsearch
      command: systemctl restart elasticsearch.service

    - name: Restart Kibana
      command: systemctl restart kibana.service

    - name: Restart Logstash
      command: systemctl restart logstash.service

    - name: Restart firewalld
      command: systemctl restart firewalld.service

    - name: Restart daemon
      command: systemctl daemon-reload


##---
#
#This is Filebeat v6.0.1
#

- hosts: testers
  remote_user: root

  tasks:
    - name: Download Filebeat
      command: wget https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.0.1-x86_64.rpm
      ignore_errors: true
      become: true

    - name: Install Filebeat
      command: yum -y install filebeat-6.0.1-x86_64.rpm
      ignore_errors: true
      become: true

    - name: Edit Kibana port to Open in config file
      lineinfile:
        destfile: /etc/filebeat/filebeat.yml
        line: 'host:"192.168.2.199:5601"'
        insertafter: '^setup.kibana:'

    - name: Start Filebeat
      command: systemctl start filebeat.service

    - name: Enable Filebeat
      command: systemctl enable filebeat.service

    - pause:
        seconds: 30

    - name: Restart Elasticsearch
      command: systemctl restart elasticsearch.service

    - name: Restart Kibana
      command: systemctl restart kibana.service

    - name: Restart Logstash
      command: systemctl restart logstash.service

    - name: Restart firewalld
      command: systemctl restart firewalld.service

    - name: Restart daemon
      command: systemctl daemon-reload


##---
#
#This is Heartbeat v6.0.1
#

- hosts: testers
  remote_user: root

  tasks:
    - name: Download Heartbeat
      command: wget https://artifacts.elastic.co/downloads/beats/heartbeat/heartbeat-6.0.1-x86_64.rpm
      ignore_errors: true
      become: true

    - name: Install Heartbeat
      command: yum -y install heartbeat-6.0.1-x86_64.rpm
      ignore_errors: true
      become: true

    - name: Edit Kibana port to Open in config file
      lineinfile:
        destfile: /etc/heartbeat/heartbeat.yml
        line: 'host:"192.168.2.199:5601"'
        insertafter: '^setup.kibana:'

    - name: Start Heartbeat
      command: systemctl start heartbeat-elastic.service

    - name: Enable Heartbeat
      command: systemctl enable heartbeat-elastic.service

    - pause:
        seconds: 30

    - name: Restart Elasticsearch
      command: systemctl restart elasticsearch.service

    - name: Restart Kibana
      command: systemctl restart kibana.service

    - name: Restart Logstash
      command: systemctl restart logstash.service

    - name: Restart firewalld
      command: systemctl restart firewalld.service

    - name: Restart daemon
      command: systemctl daemon-reload




