##### This is for Updating EPEL #####

---
#
#This is for Updating EPEL
#

- hosts: all
  remote_user: root

  tasks:
    - name: EPEL Update
      command: yum -y install epel-release


##### This is for Installing Redis #####

##---
#
#This is for Installing Redis
#

- hosts: all
  remote_user: root

  tasks:
    - name: Install Redis
      command: yum -y install redis

    - name: Start Redis
      command: systemctl start redis

    - name: Enable Redis
      command: systemctl enable redis

    - name: Check Redis
      command: redis-cli ping


##### This is to Configure Redis #####

##---
#
#This if for Configure Redis
#

- hosts: all
  remote_user: root

  tasks:
    - name: Persistence Options
      lineinfile:
        destfile: /etc/redis.conf
        regexp: 'appendonly no'
        line: 'appendonly yes'

    - pause:
        seconds: 30

    - name: Restart Redis
      command: systemctl restart redis


##### This is to Tune Redis #####

##---
#
#This if for Tune Redis
#

- hosts: all
  remote_user: root

  tasks:
    - name: Restart Redis
      command: sysctl vm.overcommit_memory=1

    - name: Restart Redis
      command: systemctl restart redis


##### This is to Configure Redis Master Node #####

##---
#
#This if for Configure Redis Master Node
#

- hosts: Master
  remote_user: root

  tasks:
    - name: Persistence Options
      lineinfile:
        destfile: /etc/redis.conf
        regexp: 'bind 127.0.0.1'
        line: 'bind 127.0.0.1 192.168.2.182'

    - pause:
        seconds: 30

    - name: Restart Redis
      command: systemctl restart redis


##### This is to Configure Redis Slave Node #####

##---
#
#This if for Configure Redis Slave Node
#

- hosts: Client
  remote_user: root

  tasks:
    - name: Persistence Options
      lineinfile:
        destfile: /etc/redis.conf
        regexp: '# slaveof <masterip> <masterport>'
        line: 'slaveof 192.168.2.182 6379'

    - pause:
        seconds: 30

    - name: Restart Redis
      command: systemctl restart redis


##### This is to Configure Master Password #####

##---
#
#This if for Configure Password
#

- hosts: Master
  remote_user: root

  tasks: 
    - name: Set Master Password
      lineinfile:
        destfile: /etc/redis.conf
        regexp: '# requirepass foobared'
        line: 'requirepass password'

    - pause:
        seconds: 30

    - name: Restart Redis
      command: systemctl restart redis


##### This is to Configure Slave Password #####

##---
#
#This if for Configure Password
#

- hosts: Client
  remote_user: root

  tasks: 
    - name: Set Slave Password
      lineinfile:
        destfile: /etc/redis.conf
        regexp: '# requirepass foobared'
        line: 'requirepass password'

    - pause:
        seconds: 30

    - name: Restart Redis
      command: systemctl restart redis


